name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build
        run: |
          npm install
          npm install dotenv
        env:
          APP_API_KEY: ${{ secrets.GEMINI_API}}
          MAP_API_KEY: ${{ secrets.MAP_API}}
